### ISSUE TITLE
any plan to support source map

### ISSUE THREAD

**Issue by avocadee** [tntim96/JSCover2#13]
Hello, I am wondering if you have plan to support source map for code coverage report or not. Thanks

**Comment by tntim96** [comment]
With the closure compiler this should be possible. How exactly would you want it to work?

Run tests on minified code and use source-map to get a nice coverage report on the original source?

**Comment by Heeseong** [comment]
Hi tntim96,

I'd like to measure code coverage from chucked files +sourcemap. It means that remapping are required.
The code is not minified. 
I do not use original source for code coverage.

**Comment by kathxqq** [comment]
> Run tests on minified code and use source-map to get a nice coverage report on the original source?
 we want to do this ,do you have any plan to support this .  
[https://github.com/tntim96/JSCover/issues/224](url)
i've seen #224, how is the contribution about sourcemap going on ? @tntim96 @karottenreibe
